on:
  push:
    branches:
      - main
jobs:
  follow_unfollow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.6

      - name: Run script
        run: go run main.go
        env:
          MY_PAT: ${{ secrets.PAT }}
