on:
  schedule:
    - cron: "0 5 * * *"
    - cron: "0 17 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  follow_unfollow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.6

      - name: Run script
        run: go run main.go
        env:
          MY_PAT: ${{ secrets.PAT }}

      - name: Add timestamp to log
        run: |
          echo "Generated on: $(date)" >> log.txt
          echo "Repository: ${{ github.repository }}" >> log.txt
          echo "Commit: ${{ github.sha }}" >> log.txt

      - name: Commit and push log file
        run: |
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
          git config --local user.name "${{ secrets.GIT_NAME }}"
          git add log.txt
          git diff --staged --quiet || git commit -m "log - $(date '+%Y-%m-%d')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
